# Python Arrays:

An array is defined as a collection of items that are stored at contiguous memory locations.

It is a container which can hold a fixed number of items, and these items should be of the same type.

Array is an idea of storing multiple items of the same type together and it makes easier to calculate the position of each element by simply adding an offset to the base value.

Array Representation:

The important points that should be considered are as follows:

1. Index starts with 0.
2. We can access each element via its index.
3. The length of the array defines the capacity to store the elements.:


### Array operations:
    
Some of the basic operations supported by an array are as follows:

1. Traverse - It prints all the elements one by one.
2. Insertion - It adds an element at the given index.
3. Deletion - It deletes an element at the given index.
4. Search - It searches an element using the given index or by the value.
5. Update - It updates an element at the given index.


from array import *  
arrayName = array(typecode, [initializers])   

### Accessing array elements:

In [1]:
import array as arr  
a = arr.array('i', [2, 4, 6, 8])  
print("First element:", a[0])  
print("Second element:", a[1])  
print("Second last element:", a[-1])  

First element: 2
Second element: 4
Second last element: 8


In [2]:
import array as arr
a=arr.array('i',[2,3,4,5,6,7,8,9,10,11,12,13,14,15])

print(a)

array('i', [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15])


In [3]:
a[0]

2

In [4]:
a[4:8]

array('i', [6, 7, 8, 9])

In [5]:
#Access last element of the array
a[-1]

15

In [6]:
#Reverse the array

a[::-1]

array('i', [15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2])

In [7]:
#find the lenght of array

len(a)

14

In [8]:
#delete a element

del a[0]

In [9]:
print(a)

array('i', [3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15])


# Numpy:

NumPy stands for numeric python which is a python package for the computation and processing of the multidimensional and single dimensional array elements.


There are the following advantages of using NumPy for data analysis:

1. NumPy performs array-oriented computing.
2. It efficiently implements the multidimensional arrays.
3. It performs scientific computations.
4. It is capable of performing Fourier Transform and reshaping the data stored in multidimensional arrays.
5. NumPy provides the in-built functions for linear algebra and random number generation.

NumPy is so important for numerical computations in Python is because it is designed for efficiency on large arrays of data.

There are a number of reasons for this:

• NumPy internally stores data in a contiguous block of memory, independent of other built-in Python objects. NumPy’s library of algorithms written in the C language can operate on this memory without any type checking or other overhead.NumPy arrays also use much less memory than built-in Python sequences.

• NumPy operations perform complex computations on entire arrays without the need for Python for loops.

### NumPy Environment Setup:
    $ pip install numpy   

## NumPy Ndarray: A Multidimensional Array Object

What is Ndarray?

Ndarray is the n-dimensional array object.

Ndarray stores collection of similar type of elements.

Ndarray, an efficient multidimensional array providing fast array-oriented arithmetic operations and flexible broadcasting capabilities.

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

### Creating a ndarray object:

The ndarray object can be created by using the array routine of the numpy module.

Syntax:

numpy.array(object, dtype = None, copy = True, order = None, subok = False, ndmin = 0) 

1. object :	It represents the collection object. It can be a list, tuple, dictionary, set, etc.
2. dtype  :	We can change the data type of the array elements by changing this option to the specified type. The default is none.
3. copy   :	It is optional. By default, it is true which means the object is copied.
4. order  :	There can be 3 possible values assigned to this option. It can be C (column order), R (row order), or A (any)
5. subok  :	The returned array will be base class array by default. We can change this to make the subclasses passes through by setting this option to true.
6. ndmin  :	It represents the minimum dimensions of the resultant array.

In [20]:
a=np.array([[1,2,3],[2,3,4]])
print(a)

[[1 2 3]
 [2 3 4]]


In [21]:
type(a)

numpy.ndarray

In [22]:
a.shape

(2, 3)

### ndim:
    
The ndim function can be used to find the dimensions of the array

In [27]:
#Finding the dimensions of the Array
a.ndim

2

In [23]:
b=np.random.randn(3,3)

In [24]:
print(b)

[[-1.76933953  0.45106927  0.54359636]
 [-0.92016322  0.16327095 -2.22713391]
 [-0.0107659  -1.60183263 -0.75150973]]


In [25]:
b.shape

(3, 3)

In [26]:
#Finding the dimensions of the Array
a.ndim

2

In [28]:
c=np.array([1,2,3,4],complex)
print(c)

[1.+0.j 2.+0.j 3.+0.j 4.+0.j]


### Finding the size of each array element:

The itemsize function is used to get the size of each array item. It returns the number of bytes taken by each array element.

In [33]:
import numpy as np  
a = np.array([1,2,3])
a.itemsize

4

### Finding the data type of each array item:
To check the data type of each array item, the dtype function is used.

In [35]:
import numpy as np
a=np.array([[1,2,3,4],[23.0,24,25,26]])
a.dtype

dtype('float64')

### Finding the shape and size of the array
To get the shape and size of the array, the size and shape function associated with the numpy array is used.

In [36]:
a.size

8

In [37]:
a.shape

(2, 4)

### Reshaping the array objects:

The reshape() function associated with the ndarray object is used to reshape the array. 

It accepts the two parameters indicating the row and columns of the new shape of the array.

In [39]:
b=np.array([[1,2],[3,4],[5,6],[7,8],[0,1]])
print(b.shape)

(5, 2)


In [40]:
print(b)

[[1 2]
 [3 4]
 [5 6]
 [7 8]
 [0 1]]


In [41]:
b.reshape(2,5)

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 0, 1]])

### Slicing in the Array:

Slicing in the NumPy array is the way to extract a range of elements from an array.

In [42]:
a1=np.array([[1,2],[2,3],[4,5]])
print(a1)

[[1 2]
 [2 3]
 [4 5]]


In [44]:
a1[0,0]

1

In [45]:
a1[0,1]

2

In [46]:
a1[1,0]

2

In [47]:
a1[1,1]

3

In [48]:
a1[2,0]

4

In [49]:
a1[2,1]

5

# Numpy:

list can be converted as numpy array.

In [1]:
l1=[1,2,3,4,5]
import numpy as np
A1=np.array(l1)
A1

array([1, 2, 3, 4, 5])

In [2]:
#Dimensions of the array
A1.ndim

1

In [4]:
#Shape of the array
A1.shape

(5,)

Note:reshape() is the function which can be used to reshape the array.

In [13]:
#dtype is used to know the type of the elements of the array
A1.dtype

dtype('int32')

In [16]:
A2=np.array([[1,"a",2,"b",3],[2,3,4,5,"l"]])

In [17]:
A2.ndim

2

In [18]:
A2

array([['1', 'a', '2', 'b', '3'],
       ['2', '3', '4', '5', 'l']], dtype='<U11')

In [50]:
A2.shape

(2, 5)

In [63]:
A2[:1][0][1:2]

array(['a'], dtype='<U11')

In [65]:
A2[:1][0][3:4]

array(['b'], dtype='<U11')

In [84]:
b2=A2.reshape(5,2)
b2

array([['1', 'a'],
       ['2', 'b'],
       ['3', '2'],
       ['3', '4'],
       ['5', 'l']], dtype='<U11')

In [83]:
b2[:1][0][1]

'a'

In [87]:
b2[:2][1][1]

'b'

In [88]:
b2[:3][2][1]

'2'

In [92]:
B3=np.arange(10).reshape((5,2))
B3

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [95]:
B3[:1][0][1]

1

In [97]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Now let's discuss easier way to get elements from array:

Individual elements can be accessed recursively. But that is a bit too much work, so you can pass a comma-separated list of indices to select individual elements.

In [100]:
arr2d[1,2]

6

In [112]:
arr2d[:2][1][2]

6

In [110]:
arr2d[:3][2][2]

9

In [113]:
arr2d[2,2]

9

In [114]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [115]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [123]:
arr3d[:1][0][0][2]

3

In [126]:
arr3d[0,0,2]

3

Note:one-dimensional objects such as Python lists, ndarrays can be sliced with the familiar syntax.

In [128]:
arr1d=np.array([1,2,3,4,5,6,7,8,9])

In [137]:
type(arr1d.mean())

numpy.float64

randn :it generates some random data.

In [1]:
import numpy as np

In [7]:
N1=np.random.randn(2,2)
N1

array([[-0.64157037,  1.66045971],
       [-1.40205364,  0.90048658]])

In [13]:
import numpy as np
N2=np.random.randint(5,size=(2,3))
N2

array([[1, 3, 3],
       [2, 2, 0]])

In [15]:
#2-D Array
N3=np.random.rand(2,3)
N3

array([[0.10696567, 0.42978488, 0.99050401],
       [0.13230891, 0.08608944, 0.51162509]])

In [26]:
#3-D Array
N4=np.random.rand(2,2,2)
N4

array([[[0.82368939, 0.96114059],
        [0.7608373 , 0.86925272]],

       [[0.53433393, 0.84650405],
        [0.92418531, 0.91503623]]])

We can explicitly convert or cast an array from one dtype to another using ndarray’s
astype method:

astype()

In [10]:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int32')

In [13]:
#Now change the data type:
n_arr=arr.astype(np.float)

<ipython-input-13-51f843d015eb>:2: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  n_arr=arr.astype(np.float)


In [14]:
n_arr.dtype

dtype('float64')

In [5]:
import numpy as np
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr.dtype


dtype('float64')

In [7]:
arr1=arr.astype(np.int32)
arr1


array([ 3, -1, -2,  0, 12, 10])

In [8]:
arr1.dtype

dtype('int32')

Note:Calling astype always creates a new array (a copy of the data), even if the new dtype is the same as the old dtype.

## Numpy:Basic Indexing and Slicing

Slicing is nothing but it's a way of selecting a subset of data or individual data

In [28]:
arr=np.arange(8)
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

slicing the elements from 1-d array is similar to slicing elements from a list.

In [29]:
arr[0]

0

In [30]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [31]:
arr[2:4]

array([2, 3])

In [2]:
import numpy as np
arr = np.arange(10)

In [3]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr[5:8]

array([5, 6, 7])

In [5]:
arr[5:8]=12

In [6]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

Note:When we assign a scalar value to a slice, as in arr[5:8] = 12, the value is propagated (or broadcasted henceforth) to the entire selection. An important first distinction from Python’s built-in lists is that array slices are views on the original array.This means that the data is not copied, and any modifications to the view will be reflected in the source array.

In [7]:
l1=[1,2,3,4,5,6,7,8,9]
l1[5:8]

[6, 7, 8]

In [8]:
l1[5:8]=2

TypeError: can only assign an iterable

In [10]:
arr_slice=arr[5:8]

In [11]:
arr_slice[1]=12345

In [12]:
arr_slice

array([   12, 12345,    12])

In [13]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

The "bare” slice [:] will assign to all values in an array:

In [14]:
arr_slice[:]=1

In [15]:
arr

array([0, 1, 2, 3, 4, 1, 1, 1, 8, 9])

In [18]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
arr2d[0]

array([1, 2, 3])

In [22]:
arr2d[1]

array([4, 5, 6])

In [23]:
arr2d[2]

array([7, 8, 9])

In [24]:
arr2d[2][0]

7

In [25]:
#Another way to get element:
arr2d[2,0]

7

In [26]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [27]:
#Dimensions of error
arr3d.ndim

3

In [28]:
#Shape of array
arr3d.shape

(2, 2, 3)

In [29]:
#Note:To get or slice 3-d array ,we need to pass three indexes
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
arr3d[1]

array([[ 7,  8,  9],
       [10, 11, 12]])

In [33]:
arr3d[0,0,2]

3

In [34]:
arr3d[1,1,2]

12

In [1]:
import numpy as np
arr3d=np.array([[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])

In [2]:
arr3d


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
arr3d[:2][0]

array([1, 2, 3])

#Example of Broadcasting

In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3,4,5,6,7,8,9,0])
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [3]:
arr_slice=arr[4:8]
arr_slice

array([5, 6, 7, 8])

In [4]:
arr_slice[:]=1

In [5]:
arr

array([1, 2, 3, 4, 1, 1, 1, 1, 9, 0])

# Some Import for numpy array object:

1. ndim: This gives the number of dimensions of the array.

2. shape: This gives the size of each dimension of the array:

3. size: This gives the number of elements:

4. dtype: This gives the datatype of the elements in the array:



In [6]:
arr.ndim

1

In [8]:
arr.shape

(10,)

In [9]:
arr.size

10

In [10]:
arr.dtype

dtype('int32')

In [11]:
arr.transpose

<function ndarray.transpose>

In [12]:
arr

array([1, 2, 3, 4, 1, 1, 1, 1, 9, 0])

# So far we have learnt many thing but now it's time to get your hand dirty with some real stuff. So let's get started:
Wine dataset.

In [1]:
import csv 
with open("winequality-red.csv", 'r') as f:
    wines = list(csv.reader(f, delimiter=";"))
import numpy as np
wine_arr=np.array(wines[1:],dtype=float)

In [53]:
wines[1:][1:2]

[['7.8',
  '0.88',
  '0',
  '2.6',
  '0.098',
  '25',
  '67',
  '0.9968',
  '3.2',
  '0.68',
  '9.8',
  '5']]

In [54]:
wine_arr.shape

(1599, 12)

In [55]:
wine_arr.ndim

2

In [56]:
wine_arr.dtype

dtype('float64')

In [57]:
wine_arr

array([[ 7.4  ,  0.7  ,  0.   , ...,  0.56 ,  9.4  ,  5.   ],
       [ 7.8  ,  0.88 ,  0.   , ...,  0.68 ,  9.8  ,  5.   ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  0.65 ,  9.8  ,  5.   ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  0.75 , 11.   ,  6.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  0.71 , 10.2  ,  5.   ],
       [ 6.   ,  0.31 ,  0.47 , ...,  0.66 , 11.   ,  6.   ]])

# As we know in array like a list indexing starts with 0. It means your first row index would be 0 in numpy array too.

In [65]:
wine_arr[0,0] # first element of your array(0,0)

7.4

In [58]:
wine_arr[1,0].astype(int)

7

In [67]:
wine_arr[:,0].astype(int)

array([7, 7, 7, ..., 6, 5, 6])

In [61]:
#another way of reading csv or txt file in numpy
wines1 = np.genfromtxt("winequality-red.csv", delimiter=";", skip_header=1)

In [63]:
wines1

array([[ 7.4  ,  0.7  ,  0.   , ...,  0.56 ,  9.4  ,  5.   ],
       [ 7.8  ,  0.88 ,  0.   , ...,  0.68 ,  9.8  ,  5.   ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  0.65 ,  9.8  ,  5.   ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  0.75 , 11.   ,  6.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  0.71 , 10.2  ,  5.   ],
       [ 6.   ,  0.31 ,  0.47 , ...,  0.66 , 11.   ,  6.   ]])


# NumPy Array Methods

In [9]:
#sum of values at column level
wine_arr[:,1].sum()

843.985

In [14]:
#sum of values at row level
wine_arr[2].sum()

99.69900000000001

In [15]:
# sum of values at column level(all columns)
wine_arr.sum(axis=0)

array([13303.1    ,   843.985  ,   433.29   ,  4059.55   ,   139.859  ,
       25384.     , 74302.     ,  1593.79794,  5294.47   ,  1052.38   ,
       16666.35   ,  9012.     ])

In [12]:
#Sum of values at row level.(all rows)
wine_arr.sum(axis=1)

array([ 74.5438 , 123.0548 ,  99.699  , ..., 100.48174, 105.21547,
        92.49249])

In [5]:
# sum of values at column level
wine_arr.sum(axis=0)

array([13303.1    ,   843.985  ,   433.29   ,  4059.55   ,   139.859  ,
       25384.     , 74302.     ,  1593.79794,  5294.47   ,  1052.38   ,
       16666.35   ,  9012.     ])

There are lot more methods which can be used to fulfill different objectives.
few are below:
1. numpy.ndarray.mean — finds the mean of an array.
2. numpy.ndarray.std — finds the standard deviation of an array.
3. numpy.ndarray.min — finds the minimum value in an array.
4. numpy.ndarray.max — finds the maximum value in an array.
and list goes on....

In [16]:
wine_arr.mean(axis=0)

array([ 8.31963727,  0.52782051,  0.27097561,  2.5388055 ,  0.08746654,
       15.87492183, 46.46779237,  0.99674668,  3.3111132 ,  0.65814884,
       10.42298311,  5.63602251])

In [17]:
wine_arr[2].mean()

8.308250000000001

In [18]:
wine_arr[1].max()

67.0

In [20]:
wine_arr[1].min()

0.0

In [22]:
wine_arr_copy=wine_arr[1].copy(order='C')

In [23]:
wine_arr_copy

array([ 7.8   ,  0.88  ,  0.    ,  2.6   ,  0.098 , 25.    , 67.    ,
        0.9968,  3.2   ,  0.68  ,  9.8   ,  5.    ])

In [32]:
number=()
y=list(number)
for x in range(15):
    y.append(x)
number=tuple(y)
number[1:12:2]
    

(1, 3, 5, 7, 9, 11)

In [35]:
Customer1={"CutomerNo":1,"name":"Chandra","DOB":"03-08-1990","PurchaseAmount":2500}
Customer1["PurchaseAmount"]=25000

In [36]:
Customer1

{'CutomerNo': 1,
 'name': 'Chandra',
 'DOB': '03-08-1990',
 'PurchaseAmount': 25000}

In [47]:
L1=[]
L2=[]
for i in Customer1:
    L2.append(i)
    L1.append(Customer1[i])

In [46]:
L1

[1, 'Chandra', '03-08-1990', 25000]

In [48]:
L2

['CutomerNo', 'name', 'DOB', 'PurchaseAmount']

In [51]:
Customer1.items()

dict_items([('CutomerNo', 1), ('name', 'Chandra'), ('DOB', '03-08-1990'), ('PurchaseAmount', 25000)])

In [52]:
Customer1.values()

dict_values([1, 'Chandra', '03-08-1990', 25000])

In [53]:
Customer1.keys()

dict_keys(['CutomerNo', 'name', 'DOB', 'PurchaseAmount'])

In [54]:
for x,y in Customer1.items():
    print(x,y)

CutomerNo 1
name Chandra
DOB 03-08-1990
PurchaseAmount 25000


# NumPy Array Comparisons
comparison operations like <, >, >=, <=, and ==. 

In [57]:
wine_arr

array([[ 7.4  ,  0.7  ,  0.   , ...,  0.56 ,  9.4  ,  5.   ],
       [ 7.8  ,  0.88 ,  0.   , ...,  0.68 ,  9.8  ,  5.   ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  0.65 ,  9.8  ,  5.   ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  0.75 , 11.   ,  6.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  0.71 , 10.2  ,  5.   ],
       [ 6.   ,  0.31 ,  0.47 , ...,  0.66 , 11.   ,  6.   ]])

In [66]:
wine_arr[:2,1]>0.7

array([False,  True])

In [68]:
high_quality_and_alcohol = (wine_arr[:,10] > 10) & (wine_arr[:,11] > 7)

In [72]:
print(high_quality_and_alcohol[True])

[[False False False ... False False False]]


In [74]:
wine_arr.shape

(1599, 12)

In [75]:
wine_arr.reshape(12,1599)

array([[7.40000e+00, 7.00000e-01, 0.00000e+00, ..., 6.60000e+00,
        5.00000e-01, 1.00000e-02],
       [1.50000e+00, 6.00000e-02, 1.70000e+01, ..., 3.30000e+00,
        9.60000e-02, 2.60000e+01],
       [6.10000e+01, 1.00025e+00, 3.60000e+00, ..., 4.20000e+01,
        9.96300e-01, 3.10000e+00],
       ...,
       [2.30000e+00, 7.60000e-02, 2.30000e+01, ..., 1.70000e+00,
        7.50000e-02, 6.00000e+00],
       [2.50000e+01, 9.95810e-01, 3.09000e+00, ..., 5.30000e+01,
        9.95800e-01, 3.41000e+00],
       [6.70000e-01, 9.70000e+00, 5.00000e+00, ..., 6.60000e-01,
        1.10000e+01, 6.00000e+00]])

In [76]:
wine_arr.shape

(1599, 12)

In [77]:
wine_arr.reshape(12,1599)

array([[7.40000e+00, 7.00000e-01, 0.00000e+00, ..., 6.60000e+00,
        5.00000e-01, 1.00000e-02],
       [1.50000e+00, 6.00000e-02, 1.70000e+01, ..., 3.30000e+00,
        9.60000e-02, 2.60000e+01],
       [6.10000e+01, 1.00025e+00, 3.60000e+00, ..., 4.20000e+01,
        9.96300e-01, 3.10000e+00],
       ...,
       [2.30000e+00, 7.60000e-02, 2.30000e+01, ..., 1.70000e+00,
        7.50000e-02, 6.00000e+00],
       [2.50000e+01, 9.95810e-01, 3.09000e+00, ..., 5.30000e+01,
        9.95800e-01, 3.41000e+00],
       [6.70000e-01, 9.70000e+00, 5.00000e+00, ..., 6.60000e-01,
        1.10000e+01, 6.00000e+00]])

In [83]:
wine_ra=wine_arr.ravel()
wine_ra[1250]

0.24

In [80]:
wine_arr.shape

(1599, 12)

# Combining NumPy Arrays

lets talk about how to combine two arrays.

In [86]:
wine_white=np.genfromtxt("winequality-white.csv",delimiter=";",skip_header=1)
wine_white

array([[ 7.  ,  0.27,  0.36, ...,  0.45,  8.8 ,  6.  ],
       [ 6.3 ,  0.3 ,  0.34, ...,  0.49,  9.5 ,  6.  ],
       [ 8.1 ,  0.28,  0.4 , ...,  0.44, 10.1 ,  6.  ],
       ...,
       [ 6.5 ,  0.24,  0.19, ...,  0.46,  9.4 ,  6.  ],
       [ 5.5 ,  0.29,  0.3 , ...,  0.38, 12.8 ,  7.  ],
       [ 6.  ,  0.21,  0.38, ...,  0.32, 11.8 ,  6.  ]])

In [87]:
wine_white.shape

(4898, 12)

In [95]:
wine_arr.shape

(1599, 12)

In [92]:
all_wine=np.vstack((wine_arr,wine_white))

Note:numpy.vstack to vertically stack multiple arrays. Think of it like the second arrays’s items being added as new rows to the first array. 

In [93]:
all_wine.shape

(6497, 12)

In [96]:
all_wine=np.hstack((wine_arr,wine_white))

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 1599 and the array at index 1 has size 4898

If we want to combine arrays horizontally, where the number of rows stay constant, but the columns are joined, 
then we can use the numpy.hstack function. The arrays we combine need to have the same number of rows for this to work.

In [97]:
all_wines=np.concatenate((wine_arr,wine_white),axis=0)   # same as vstack

In [98]:
all_wines.shape

(6497, 12)

In [99]:
all_wines=np.concatenate((wine_arr,wine_white),axis=1)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 1599 and the array at index 1 has size 4898

Some More Excercises: